### ISSUE TITLE
Crash start game [1.15.2] [Fabric]

### ISSUE THREAD

**Issue by Sepera-okeq** [jellysquid3/phosphor-fabric#2]
Works unstable, works every other time. These types of errors are thrown:
Game version: 1.15.2

```[19:20:49] [main/INFO]: Loading for game Minecraft 1.15.2
[19:20:53] [main/WARN]: Mod `clear-skies` (1.1.19) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[19:20:53] [main/INFO]: [FabricLoader] Loading 56 mods: fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.7.8+build.189, customskinloader@14.12-SNAPSHOT-109, org_zeroturnaround_zt-zip@1.14, lithium@0.4.6, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-api-base@0.1.2+b7f9825d0c, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-textures-v0@1.0.4+821cdba70c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, com_moandjiezana_toml_toml4j@0.7.2, cotton-logging@1.0.0-rc.4, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.5.1+build.294-1.15, dynamicfps@1.1.1, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-networking-v0@0.1.7+12515ed90c, cloth@1.2.0, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, runorama@0.2.4, modmenu@1.10.2+build.32, cloth-basic-math@0.4.1, phosphor@0.5.2+build.6, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-biomes-v1@0.1.5+3b05f68e0c, org_slf4j_slf4j-simple@1.7.30, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.3.0+fac69e320c, roughlyenoughitems@3.6.6, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.13.1, smoothscrollingeverywhere@2.4.1, autoconfig1u@2.0, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, optifabric@1.0.0-beta8, window_title_changer@1.1.0-1.15, clear-skies@1.1.19, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, uselesstutorial@1.0.0, fabric-object-builders-v0@0.1.3+e4c9a9c30c, org_jetbrains_annotations@18.0.0
[19:20:53] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Andrey/AppData/Roaming/DTC/updates/SPVanila/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[19:20:55] [main/INFO]: Lithium's configuration file was loaded successfully
[19:20:55] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.chunk.no_chunk_locking.MixinPalettedContainer' as no configuration enables it
[19:20:55] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinRedstoneWireBlock' as no configuration enables it
[19:20:55] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinWorld' as no configuration enables it
Optifabric is still using the traditional Early Riser initialisation
Found existing patched optifine jar, using that
[19:20:57] [main/INFO]: [OptiFine] *** Reflector Forge ***
[19:20:57] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[19:20:57] [main/WARN]: Error loading class: net/fabricmc/fabric/api/event/Event (java.lang.ClassNotFoundException: net/fabricmc/fabric/api/event/Event)
org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for cloth.mixins.json:MixinScreen during activity: [Transform -> Method onPreDraw(IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> net/fabricmc/fabric/api/event/Event::invoker()Ljava/lang/Object;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:176)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:414)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.DTCThjaiBGOywt.dtchPx50mq6tZI(Unknown Source)
	at pro.gravit.launcher.DTCThjaiBGOywt.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.Event
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:720)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
	... 27 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.Event
	... 31 more
2020.04.11 19:20:57 [ERROR] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2020.04.11 19:20:57 [INFO] WebSocket client disconnect
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Process exit code 0```

**Comment by eatmyvenom** [comment]
In what way does this error pertain to phosphor?

**Comment by liach** [comment]
Install fabric api. https://www.curseforge.com/minecraft/mc-mods/fabric-api/

**Comment by jellysquid3** [comment]
This issue is not caused by Phosphor. Your mod configuration is broken, see above.
