### ISSUE TITLE
Game freezes when generating chunks in the nether

### ISSUE THREAD

**Issue by Mewtwoy** [jellysquid3/phosphor-fabric#29]
Worker-Main-17 died
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.light.LightStorage.get(LightStorage:655) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkLightProvider.getLevel(ChunkLightProvider:143) ~[?:?]
	at net.minecraft.world.chunk.light.LevelPropagator.updateLevel(LevelPropagator:137) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkBlockLightProvider.addLightSource(ChunkBlockLightProvider:129) ~[?:?]
	at net.minecraft.world.chunk.light.LightingProvider.addLightSource(LightingProvider:41) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_14275(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$8549/358747071.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.server.world.ServerLightingProvider.method_17312(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7359/416017512.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.runTasks(ServerLightingProvider:170) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_19505(ServerLightingProvider:155) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7345/974139227.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[Worker-Main-17/ERROR]: Caught exception in thread Thread[Worker-Main-17,8,main]
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.light.LightStorage.get(LightStorage:655) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkLightProvider.getLevel(ChunkLightProvider:143) ~[?:?]
	at net.minecraft.world.chunk.light.LevelPropagator.updateLevel(LevelPropagator:137) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkBlockLightProvider.addLightSource(ChunkBlockLightProvider:129) ~[?:?]
	at net.minecraft.world.chunk.light.LightingProvider.addLightSource(LightingProvider:41) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_14275(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$8549/358747071.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.server.world.ServerLightingProvider.method_17312(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7359/416017512.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.runTasks(ServerLightingProvider:170) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_19505(ServerLightingProvider:155) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7345/974139227.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
[Worker-Main-28/WARN]: Worker-Main-28 died
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.light.LightStorage.get(LightStorage:655) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkLightProvider.getLevel(ChunkLightProvider:143) ~[?:?]
	at net.minecraft.world.chunk.light.LevelPropagator.updateLevel(LevelPropagator:137) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkBlockLightProvider.addLightSource(ChunkBlockLightProvider:129) ~[?:?]
	at net.minecraft.world.chunk.light.LightingProvider.addLightSource(LightingProvider:41) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_14275(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$8549/358747071.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.server.world.ServerLightingProvider.method_17312(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7359/416017512.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.runTasks(ServerLightingProvider:170) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_17313(ServerLightingProvider:108) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7306/596442023.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.class_3900$$Lambda$7321/337116529.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[Worker-Main-28/ERROR]: Caught exception in thread Thread[Worker-Main-28,8,main]
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.light.LightStorage.get(LightStorage:655) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkLightProvider.getLevel(ChunkLightProvider:143) ~[?:?]
	at net.minecraft.world.chunk.light.LevelPropagator.updateLevel(LevelPropagator:137) ~[?:?]
	at net.minecraft.world.chunk.light.ChunkBlockLightProvider.addLightSource(ChunkBlockLightProvider:129) ~[?:?]
	at net.minecraft.world.chunk.light.LightingProvider.addLightSource(LightingProvider:41) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_14275(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$8549/358747071.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.server.world.ServerLightingProvider.method_17312(ServerLightingProvider:135) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7359/416017512.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.runTasks(ServerLightingProvider:170) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_17313(ServerLightingProvider:108) ~[?:?]
	at net.minecraft.class_3227$$Lambda$7306/596442023.run(Unknown Source) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.class_3900$$Lambda$7321/337116529.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]

THE GAME HAS TO BE CLOSED USING TASK MANAGER

**Comment by PhiProven** [comment]
In which version (build number) did this happen?
Can you post the seed and coordinates where the issue occured?

**Comment by PhiProven** [comment]
Closing this as stale.
Feel free to reopen if this still happens with Phosphor 0.7.1.
