### ISSUE TITLE
1.14.x builds on CurseForge are corrupted

### ISSUE THREAD

**Issue by YukiJr** [jellysquid3/phosphor-fabric#3]
Crash after starting a version, just put the phosphor 0.3.6 that crash.

[00:07:36] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:598) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:179) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:169) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1612) ~[zipfs.jar:1.8.0_241]
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021) ~[zipfs.jar:1.8.0_241]
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030) ~[zipfs.jar:1.8.0_241]
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130) ~[zipfs.jar:1.8.0_241]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117) ~[zipfs.jar:1.8.0_241]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:1.8.0_241]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:1.8.0_241]
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:79) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:67) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:452) ~[fabric-loader-0.8.2+build.194.jar:?]
	at java.util.concurrent.RecursiveAction.exec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_241]

**Comment by jellysquid3** [comment]
Ugh. CurseForge is still corrupting files.

**Comment by YukiJr** [comment]
It's so sad.
