### ISSUE TITLE
Crash at launch (1.16.1)

### ISSUE THREAD

**Issue by Aridean** [jellysquid3/phosphor-fabric#7]
Using latest version of phosphor-fabric (0.6.0+build.7)
Fabric API (0.13.1+build.370-1.16)
Fabric Loader (0.8.8+build.202)

getting this in log:
`Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod phosphor
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:60)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.read(AccessWidener.java:78)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:58)
	... 10 more
Exiting with -1
Process exited with code 255.`

Have REI, VoxelMap, and Worldedit running as well.  no issues with them, only crashes when phosphor is enabled

-edit- in case it makes any difference:  Using MultiMC / onesix launcher

full log in pastebin [Here](https://pastebin.com/embed/qkBMdfS0)

**Comment by jellysquid3** [comment]
Please try re-downloading Phosphor 0.6.0 from CurseForge. There was a problem in the initial upload... their site is having a lot of trouble today.

**Comment by Aridean** [comment]
Aha!

good call sir. Thanks
Closed
