### ISSUE TITLE
server crashing on startup and it doesn't run in other java versions as well

### ISSUE THREAD

**Issue by warior456** [jellysquid3/phosphor-fabric#74]
error:
[17:37:40] [main/INFO]: Compatibility level set to JAVA_16
[17:37:40] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Error creating Mixin config phosphor.mixins.json for mod phosphor
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config phosphor.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]

**Comment by amnotbananaama** [comment]
Please provide the entire crash log in the future. Fortunately this issue is obvious with very little context but not all crashes are. The crash log can be found in the `crashreports` sub-folder of your server folder. 

Minecraft Java Edition 1.18 [requires a minimum of Java 17](https://www.minecraft.net/en-us/article/minecraft-1-18-pre-release-2).

**Comment by PhiProven** [comment]
This is actually a known issue with Fabric. Please reinstall using `fabric-installer >= 0.10.0`.
I have now added this information to the download pages.
