### ISSUE TITLE
Failed to launch in 1.18.1

### ISSUE THREAD

**Issue by Peter-JY** [jellysquid3/phosphor-fabric#75]
in `cmd.exe`:
> Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[09:18:50] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[09:18:51] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[09:18:51] [main/WARN]: Warnings were found!
> .- Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9565 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[09:18:51] [main/INFO]: Loading 38 mods:
        - fabric 0.45.0+1.18
        - fabric-api-base 0.4.1+b4f4f6cd65 via fabric
        - fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
        - fabric-biome-api-v1 6.0.1+ded849a965 via fabric
        - fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
        - fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
        - fabric-containers-v0 0.1.18+d154e2c665 via fabric
        - fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
        - fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
        - fabric-dimensions-v1 2.1.7+43d2957165 via fabric
        - fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
        - fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
        - fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
        - fabric-item-api-v1 1.3.0+691a79b565 via fabric
        - fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
        - fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
        - fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
        - fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
        - fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
        - fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
        - fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
        - fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
        - fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
        - fabric-particles-v1 0.2.9+526dc1ac65 via fabric
        - fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
        - fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
        - fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
        - fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
        - fabric-structure-api-v1 2.0.8+295197a765 via fabric
        - fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
        - fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
        - fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
        - fabricloader 0.12.12
        - java 17
        - minecraft 1.18.1
        - phosphor 0.8.1
[09:18:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/Peter/MinecraftServer-Fabric-1.18.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[09:18:52] [main/INFO]: Compatibility level set to JAVA_16
[09:18:52] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: java.lang.RuntimeException: Error creating Mixin config phosphor.mixins.json for mod phosphor
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config phosphor.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more

in the window of Fabric Loader, it shows these:
> java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
	... 1 more
Caused by: java.lang.RuntimeException: Error creating Mixin config phosphor.mixins.json for mod phosphor
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 6 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config phosphor.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 9 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 12 more

-----------------------------------------------------

Using Mods: `phosphor-fabric-mc1.18.x-0.8.1.jar` and `fabric-api-0.45.0+1.18.jar`
Game version: 1.18.1
Fabric version: 0.12.12

**Comment by PhiProven** [comment]
Reinstall Fabric using `fabric-installer >= 0.10.0` (see the comment on server installation on the Phosphor 1.18.x download pages).
