### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by imcasper** [jellysquid3/phosphor-fabric#76]
**java-17**
**phosphor-version 0.8.1**
**game-version 1.18.1**
**fabric-api-0.46.1+1.18.jar**
**stacktrace**
java.lang.NoSuchMethodError: 'void net.minecraft.world.chunk.light.ChunkLightProvider.method_15483(long)'
	at net.minecraft.world.chunk.light.ChunkLightProvider.cancelUpdatesForChunk(ChunkLightProvider.java:698)
	at net.minecraft.world.chunk.light.LightStorage.handler$zzc000$preRemoveSection(LightStorage.java:816)
	at net.minecraft.world.chunk.light.LightStorage.removeSection(LightStorage.java)
	at net.minecraft.world.chunk.light.LightStorage.addQueuedLightmaps(LightStorage.java:1423)
	at net.minecraft.world.chunk.light.LightStorage.updateLight(LightStorage.java:852)
	at net.minecraft.world.chunk.light.SkyLightStorage.updateLight(SkyLightStorage.java:784)
	at net.minecraft.world.chunk.light.ChunkLightProvider.doLightUpdates(ChunkLightProvider.java:186)
	at net.minecraft.world.chunk.light.LightingProvider.doLightUpdates(LightingProvider.java:65)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1211)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

PS
I'm not sure if your mod is the problem. But without it there is no error.
Probably the problem is related to an atypical situation. I use the "worldedit-mod-7.2.8.jar" to debug the ore generation mod (removing all the stones and extra blocks in a large area). And many other mods...

**Comment by PhiProven** [comment]
Sorry for the late response.
This is probably an instance of the Mixin bug https://github.com/SpongePowered/Mixin/issues/432 . As a workaround, one has to use the `-dev.jar` which, unfortunately, requires some extra steps to set things up.

**Comment by PhiProven** [comment]
Closing this due to inactivity. Feel free to reopen in case the linked Mixin issue turns out not to be the root cause.
