### ISSUE TITLE
Error: Could not load - Invalid plugin.yml - Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by harl** [jellysquid3/phosphor-fabric#9]
The following crypticle appears on our server's console when it tries to load Phosphor

[Server thread/ERROR]:  'plugins/phosphor-fabric-mc1.16.1-0.6.0+build.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: 
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-93]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.FileNotFoundException: 
	... 7 more

The mod/plugin works fine when loaded client-side (yay!), but our Paperspigot/Paperclip server seems to think that something's missing from the plugin's jar.

**Comment by jellysquid3** [comment]
Phosphor is a Fabric mod. It doesn't work on Bukkit/Spigot/Paper servers, hence why your server is confused. You need a Fabric Server installation, which means you can't carry over your existing plugins.

**Comment by harl** [comment]
Thanks. I've only used Fabric client mods yet, and didn't know (stable) server-sided Fabric is a thing now,
so I expected this to be a combined Fabric/Bukkit mod similar to Fabric/Forge combinations. My mistake.
